<?php

use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\WarehouseTransactionController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/dashboard', function () {
    return redirect()->route('admin.dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');
// auto-generated by Breeze, có thể xóa nếu không dùng
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});
//

Route::middleware('auth')->group(function () {

    // Kho: CRUD
    Route::resource('warehouse', WarehouseTransactionController::class);

    // Tồn kho
    Route::get('warehouse-ton-kho', [WarehouseTransactionController::class, 'tonKho'])
         ->name('warehouse.ton-kho');

    // ═══ Admin Dashboard ═══
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/', [AdminDashboardController::class, 'index'])->name('dashboard');

        // Users
        Route::get('users', [AdminDashboardController::class, 'users'])->name('users');
        Route::get('users/create', [AdminDashboardController::class, 'usersCreate'])->name('users.create');
        Route::post('users', [AdminDashboardController::class, 'usersStore'])->name('users.store');
        Route::get('users/{user}/edit', [AdminDashboardController::class, 'usersEdit'])->name('users.edit');
        Route::put('users/{user}', [AdminDashboardController::class, 'usersUpdate'])->name('users.update');
        Route::delete('users/{user}', [AdminDashboardController::class, 'usersDestroy'])->name('users.destroy');

        // Orders
        Route::get('orders', [AdminDashboardController::class, 'orders'])->name('orders');
        Route::get('orders/create', [AdminDashboardController::class, 'ordersCreate'])->name('orders.create');
        Route::post('orders', [AdminDashboardController::class, 'ordersStore'])->name('orders.store');
        Route::get('orders/{order}/edit', [AdminDashboardController::class, 'ordersEdit'])->name('orders.edit');
        Route::put('orders/{order}', [AdminDashboardController::class, 'ordersUpdate'])->name('orders.update');
        Route::delete('orders/{order}', [AdminDashboardController::class, 'ordersDestroy'])->name('orders.destroy');

        // Order Tracking
        Route::get('order-tracking', [AdminDashboardController::class, 'orderTracking'])->name('order-tracking');
        Route::get('order-tracking/create', [AdminDashboardController::class, 'orderTrackingCreate'])->name('order-tracking.create');
        Route::post('order-tracking', [AdminDashboardController::class, 'orderTrackingStore'])->name('order-tracking.store');
        Route::get('order-tracking/{orderTracking}/edit', [AdminDashboardController::class, 'orderTrackingEdit'])->name('order-tracking.edit');
        Route::put('order-tracking/{orderTracking}', [AdminDashboardController::class, 'orderTrackingUpdate'])->name('order-tracking.update');
        Route::delete('order-tracking/{orderTracking}', [AdminDashboardController::class, 'orderTrackingDestroy'])->name('order-tracking.destroy');

        // Production Reports
        Route::get('production-reports', [AdminDashboardController::class, 'productionReports'])->name('production-reports');
        Route::get('production-reports/create', [AdminDashboardController::class, 'productionReportsCreate'])->name('production-reports.create');
        Route::post('production-reports', [AdminDashboardController::class, 'productionReportsStore'])->name('production-reports.store');
        Route::get('production-reports/{productionReport}/edit', [AdminDashboardController::class, 'productionReportsEdit'])->name('production-reports.edit');
        Route::put('production-reports/{productionReport}', [AdminDashboardController::class, 'productionReportsUpdate'])->name('production-reports.update');
        Route::delete('production-reports/{productionReport}', [AdminDashboardController::class, 'productionReportsDestroy'])->name('production-reports.destroy');

        // Warehouse Transactions
        Route::get('warehouse-transactions', [AdminDashboardController::class, 'warehouseTransactions'])->name('warehouse-transactions');
        Route::get('warehouse-transactions/create', [AdminDashboardController::class, 'warehouseTransactionsCreate'])->name('warehouse-transactions.create');
        Route::post('warehouse-transactions', [AdminDashboardController::class, 'warehouseTransactionsStore'])->name('warehouse-transactions.store');
        Route::get('warehouse-transactions/{warehouseTransaction}/edit', [AdminDashboardController::class, 'warehouseTransactionsEdit'])->name('warehouse-transactions.edit');
        Route::put('warehouse-transactions/{warehouseTransaction}', [AdminDashboardController::class, 'warehouseTransactionsUpdate'])->name('warehouse-transactions.update');
        Route::delete('warehouse-transactions/{warehouseTransaction}', [AdminDashboardController::class, 'warehouseTransactionsDestroy'])->name('warehouse-transactions.destroy');
    });
});
require __DIR__.'/auth.php';
