<?php

use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\OrderTrackingController;
use App\Http\Controllers\Admin\ProductionReportController;
use App\Http\Controllers\Admin\WarehouseTransactionController;
use App\Http\Controllers\Admin\DanhMucHangHoaController;
use App\Http\Controllers\Admin\DanhMucKhachHangController;
use App\Http\Controllers\Staff\WarehouseEntryController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/dashboard', function () {
    $user = auth()->user();
    if ($user && $user->isStaff()) {
        return redirect()->route('staff.warehouse.index');
    }
    return redirect()->route('admin.dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');
// auto-generated by Breeze, có thể xóa nếu không dùng
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});
//

Route::middleware('auth')->group(function () {

    // ═══ Admin ═══
    Route::prefix('admin')->name('admin.')->middleware('role:admin')->group(function () {
        Route::get('/', [AdminDashboardController::class, 'index'])->name('dashboard');

        // Users
        Route::resource('users', UserController::class);

        // Orders
        Route::post('orders/import', [OrderController::class, 'import'])->name('orders.import');
        Route::post('orders/import-customer', [OrderController::class, 'importCustomer'])->name('orders.import-customer');
        Route::post('orders/assign-pl', [OrderController::class, 'assignPlNumber'])->name('orders.assign-pl');
        Route::get('orders/export', [OrderController::class, 'export'])->name('orders.export');
        Route::get('orders/template', [OrderController::class, 'template'])->name('orders.template');
        Route::resource('orders', OrderController::class);

        // Order Tracking
        Route::post('order-tracking/generate', [OrderTrackingController::class, 'generate'])
             ->name('order-tracking.generate');
        Route::post('order-tracking/push-production', [OrderTrackingController::class, 'pushToProduction'])
             ->name('order-tracking.push-production');
        Route::post('order-tracking/push-warehouse', [OrderTrackingController::class, 'pushToWarehouse'])
             ->name('order-tracking.push-warehouse');
        Route::post('order-tracking/bulk-delete', [OrderTrackingController::class, 'bulkDelete'])
             ->name('order-tracking.bulk-delete');
        Route::post('order-tracking/ship-from-stock', [OrderTrackingController::class, 'shipFromStock'])
             ->name('order-tracking.ship-from-stock');
        Route::resource('order-tracking', OrderTrackingController::class)
             ->parameters(['order-tracking' => 'orderTracking']);

        // Production Reports
        Route::resource('production-reports', ProductionReportController::class)
             ->parameters(['production-reports' => 'productionReport']);

        // Warehouse Transactions
        Route::get('warehouse-transactions/export', [WarehouseTransactionController::class, 'export'])
             ->name('warehouse-transactions.export');
        Route::get('warehouse-transactions/template', [WarehouseTransactionController::class, 'template'])
             ->name('warehouse-transactions.template');
        Route::post('warehouse-transactions/import', [WarehouseTransactionController::class, 'import'])
             ->name('warehouse-transactions.import');
        Route::get('warehouse-transactions/nhap-theo-lenh', [WarehouseTransactionController::class, 'nhapTheoLenh'])
             ->name('warehouse-transactions.nhap-theo-lenh');
        Route::post('warehouse-transactions/nhap-theo-lenh', [WarehouseTransactionController::class, 'storeNhapTheoLenh'])
             ->name('warehouse-transactions.store-nhap-theo-lenh');
        Route::get('warehouse-transactions/ton-kho', [WarehouseTransactionController::class, 'tonKho'])
             ->name('warehouse-transactions.ton-kho');
        Route::resource('warehouse-transactions', WarehouseTransactionController::class)
             ->parameters(['warehouse-transactions' => 'warehouseTransaction']);

        // Danh mục Hàng hóa
        Route::post('hang-hoa/import', [DanhMucHangHoaController::class, 'import'])->name('hang-hoa.import');
        Route::get('hang-hoa/export', [DanhMucHangHoaController::class, 'export'])->name('hang-hoa.export');
        Route::get('hang-hoa/template', [DanhMucHangHoaController::class, 'template'])->name('hang-hoa.template');
        Route::resource('hang-hoa', DanhMucHangHoaController::class)
             ->parameters(['hang-hoa' => 'hangHoa']);

        // Danh mục Khách hàng
        Route::resource('khach-hang', DanhMucKhachHangController::class)
             ->parameters(['khach-hang' => 'khachHang']);
    });

    // ═══ Nhân viên (Staff) ═══
    Route::prefix('staff')->name('staff.')->middleware('role:staff,admin')->group(function () {
        Route::get('/', fn () => redirect()->route('staff.warehouse.index'));

        // Warehouse entry
        Route::get('warehouse',       [WarehouseEntryController::class, 'index'])->name('warehouse.index');
        Route::post('warehouse',      [WarehouseEntryController::class, 'store'])->name('warehouse.store');
        Route::get('warehouse/history', [WarehouseEntryController::class, 'history'])->name('warehouse.history');
    });
});
require __DIR__.'/auth.php';
