<?php

use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\OrderTrackingController;
use App\Http\Controllers\Admin\ProductionReportController;
use App\Http\Controllers\Admin\WarehouseTransactionController;
use App\Http\Controllers\Admin\DanhMucHangHoaController;
use App\Http\Controllers\Admin\DanhMucKhachHangController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/dashboard', function () {
    return redirect()->route('admin.dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');
// auto-generated by Breeze, có thể xóa nếu không dùng
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});
//

Route::middleware('auth')->group(function () {

    // ═══ Admin ═══
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/', [AdminDashboardController::class, 'index'])->name('dashboard');

        // Users
        Route::resource('users', UserController::class);

        // Orders
        Route::post('orders/import', [OrderController::class, 'import'])->name('orders.import');
        Route::post('orders/import-customer', [OrderController::class, 'importCustomer'])->name('orders.import-customer');
        Route::get('orders/export', [OrderController::class, 'export'])->name('orders.export');
        Route::get('orders/template', [OrderController::class, 'template'])->name('orders.template');
        Route::resource('orders', OrderController::class);

        // Order Tracking
        Route::resource('order-tracking', OrderTrackingController::class)
             ->parameters(['order-tracking' => 'orderTracking']);

        // Production Reports
        Route::resource('production-reports', ProductionReportController::class)
             ->parameters(['production-reports' => 'productionReport']);

        // Warehouse Transactions
        Route::get('warehouse-transactions/ton-kho', [WarehouseTransactionController::class, 'tonKho'])
             ->name('warehouse-transactions.ton-kho');
        Route::resource('warehouse-transactions', WarehouseTransactionController::class)
             ->parameters(['warehouse-transactions' => 'warehouseTransaction']);

        // Danh mục Hàng hóa
        Route::post('hang-hoa/import', [DanhMucHangHoaController::class, 'import'])->name('hang-hoa.import');
        Route::get('hang-hoa/export', [DanhMucHangHoaController::class, 'export'])->name('hang-hoa.export');
        Route::get('hang-hoa/template', [DanhMucHangHoaController::class, 'template'])->name('hang-hoa.template');
        Route::resource('hang-hoa', DanhMucHangHoaController::class)
             ->parameters(['hang-hoa' => 'hangHoa']);

        // Danh mục Khách hàng
        Route::resource('khach-hang', DanhMucKhachHangController::class)
             ->parameters(['khach-hang' => 'khachHang']);
    });
});
require __DIR__.'/auth.php';
